### ISSUE TITLE
Could the API File.setOwner() be used to achieve the same purpose without copying?

### ISSUE THREAD

**Issue by oasisfeng** [mnpopcenter/gas-change-ownership#1]
https://developers.google.com/apps-script/reference/drive/file#setOwner(User)

I'm not sure about this as a newbie in Google Apps Scripting.

**Comment by franfabrizio** [comment]
It could if you have administrative privileges in your Google Apps environment. We don't - it's controlled centrally at the University, and this is a common problem in our sort of environment. (PS - Sorry for delayed response - just seeing this now.)

**Comment by oasisfeng** [comment]
@franfabrizio Thanks for your confirmation and this useful script!
